# PostgreSQL Connector
spring.datasource.url=jdbc:postgresql://localhost:5432/remiseria
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DDL generation
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true