name: CI Spring Boot

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18

        env:
          POSTGRES_DB: remiseria
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar proyecto
        run: ./gradlew build